version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
